spring:
  application:
    name: API1kk

  datasource:
    url: jdbc:h2:mem:api1kk
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        leak-detection-threshold: 60000

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false